# Generated by Django 5.0.4 on 2024-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_featurerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')]),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')]),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В рассмотрении'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
